version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    image: nampk96/devops_learn:{tag}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    external: true